### ISSUE TITLE
Include a lambda/package.json on create-node-lambda

### ISSUE THREAD

**Issue by radAragon** [myrmex-org/myrmex#52]
Using the command `lager create-node-lambda` creates a folder structure for the Lambda code and includes a "config.json" file with user created modules listing, but I miss a list for my external modules (node_modules) like a "package.json".

It happens a lot when using multiple endpoints with require repeating external modules.

Lager could automatically place a simplified "package.json" file with `x-lager.dependencies` for user created modules.

**Comment by AlexisNo** [comment]
Done in https://github.com/lagerjs/lager/commit/a7adb5055b14429e62207cc811c3dbc9c46a20d5

**Comment by AlexisNo** [comment]
The project dependency mechanism for Lambda modules works now like for project modules. It is configured in `package.json`.

Example:
```json
{
  "x-lager": {
    "dependencies": [
      "data-access",
      "log"
    ]
  }
}
```

Also, it is possible now to **not** provide a `package.json` file in a project module.

**Comment by radAragon** [comment]
Cheers!
