### ISSUE TITLE
Lager deploy-node-lambda Role name bug

### ISSUE THREAD

**Issue by radAragon** [myrmex-org/myrmex#53]
When deploying my Lambda with `lager deploy-node-lambda` and config.json as:
```
params: {
    Role: "role_name_not_arn"
}
```
Does not resolves the Role name to the Role ARN, and it brings the following error:
`Unhandled rejection ValidationException: 1 validation error detected: Value 'qa-cs-billing-server-r-IamRoleLambda-1KLJTGZDLEZKP' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+`

PS: plugin @lager/iam not installed on my project.

**Comment by AlexisNo** [comment]
The `@lager/iam plugin` **need** to be installed to use this functionality.

**Comment by radhomero** [comment]
Ok, but did you added a textual feedback regarding the two options for this value?

**Comment by AlexisNo** [comment]
Going to variate messages and validation when `@lager/iam plugin` is not present

**Comment by AlexisNo** [comment]
I added the notice in `lager create-node-lambda -h` and the prompt when `@lager/iam` is not available but I'm not sure we should add a validation here.

It is possible that the user does not have this information when he is using the command. He could want to quickly generate the Lambda without worrying about the role at this time or he could want to make this value configurable (via an environment variable for example).

He would be obliged to provide a fake arn that would have to be compatible with this regex: `/arn:aws:iam::\d{12}:role\/?[a-zA-Z_0-9+=,.@\-_/]+]/` to pass the prompt step. It could be very annoying.

Maybe we could provide an explicit message when performing the deployment but in this case it should apply to various other parameters too. Isn't the AWS SDK message explicit enough ?

```
Unhandled rejection ValidationException: 1 validation error detected: Value 'xxxxx' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
```

I'm closing the issue but feel free to add any thoughts.
