### ISSUE TITLE
Missing sa-east-1 region for Lambda

### ISSUE THREAD

**Issue by radAragon** [myrmex-org/myrmex#84]
Hi, i'm trying to deploy a Lambda on South America (sa-east-1) region for a job and Myrmex returns me an error:

```
sa-eat-1 is not a valid AWS region - available values: us-east-1, us-west-2, eu-west-1, eu-central-1, ap-northeast-1, ap-southeast-1
```

This Region is now available for Lambda.

I'll try to make a fork and PR, tough I assume I should first issue out the problem.

**Comment by AlexisNo** [comment]
I quickly [added other regions](https://github.com/myrmex-org/myrmex/commit/0865ca82350d24ee441b01c014d64ab14bce6a7b) for now, but there is probably a better solution.

Published in `@myrmex/lambda:0.3.2`

**Comment by radAragon** [comment]
Thanks!!

**Comment by alexmarmute** [comment]
Thanks Alexis, you`re awesome!

**Comment by AlexisNo** [comment]
It's nice to see that you continue to use Myrmex :smiley:
It will continue to evolve in 2018
