### ISSUE TITLE
An evolution for the myrmex logo

### ISSUE THREAD

**Issue by AlexisNo** [myrmex-org/myrmex#85]
I have some propositions to improve the Myrmex Logo adding an ant on it.
I'd like to have opinions about it.

* it must be easy to read "Myrmex" correctly
* one should be able to notice that the "y" is in fact a inverted "λ"
* it is possible to propose a combination of the ideas in these propositions

Thanks for your feedback

A. ![20180228_logo_myrmex-03](https://user-images.githubusercontent.com/733191/36892757-13721e3a-1e06-11e8-850b-6ec467ba0eae.png)
B. ![20180228_logo_myrmex-13](https://user-images.githubusercontent.com/733191/36892769-1aea33b4-1e06-11e8-87bf-a952ec816d05.png)
C. ![20180228_logo_myrmex-06](https://user-images.githubusercontent.com/733191/36892776-1d834160-1e06-11e8-9f61-50183af3e0af.png)
D. ![20180228_logo_myrmex-09](https://user-images.githubusercontent.com/733191/36892786-2390fc14-1e06-11e8-9a90-086323f82b70.png)
E. ![20180228_logo_myrmex-08](https://user-images.githubusercontent.com/733191/36892789-283b332e-1e06-11e8-9241-9fca822c1b0d.png)
F. ![20180228_logo_myrmex-12](https://user-images.githubusercontent.com/733191/36892791-2b896e6a-1e06-11e8-82e0-0147acd256b1.png)
G. ![20180228_logo_myrmex-10](https://user-images.githubusercontent.com/733191/36892793-2fccd34a-1e06-11e8-95ce-2a8966615393.png)
H. ![20180228_logo_myrmex-15](https://user-images.githubusercontent.com/733191/36892800-32b0f0dc-1e06-11e8-9681-b6d0a3e92f9a.png)
I. ![20180228_logo_myrmex-07](https://user-images.githubusercontent.com/733191/36893243-96a393fa-1e07-11e8-8581-eeb46d7d2e1f.png)
J. ![20180228_logo_myrmex-04](https://user-images.githubusercontent.com/733191/36893287-c817d090-1e07-11e8-9d1a-9413dfe14c86.png)
K. ![20180228_logo_myrmex-05](https://user-images.githubusercontent.com/733191/36893257-a6a249ae-1e07-11e8-9600-3718868c6ded.png)
L. ![20180228_logo_myrmex-11](https://user-images.githubusercontent.com/733191/36893261-a9f99e22-1e07-11e8-826e-dadcdb79f395.png)

**Comment by Q-Oyst** [comment]
B or G looks quite nice to me

**Comment by AlexisNo** [comment]
Those from B to G are the best for me. But I like the idea of the ant caring a piece of λ very much.

**Comment by AlexisNo** [comment]
@radAragon @caiotaniguchi @pedroorez

**Comment by agualbbus** [comment]
Hi @AlexisNo, to my understanding a logo should work at any size, for example, it should fit a business card. 

I guess that the ant figure, should have less detail, like just the ant face.

For me, E is the better choice.

**Comment by radAragon** [comment]
Hi Alexis, I like B and C because the circle around λ is more remarkable as a logo and the ant is more visible as well. However, I suggest you find a simpler ant figure, maybe more cartoonish with less parts.

**Comment by 7d4b9** [comment]
## G
I prefer G so that the ƛ is not buggy and the ant "aura" remains 

Or so I would suggest a version with multiple ants on the ƛ 😆to put forward cohesion, maybe a merge between E and F 🤔

**Comment by AlexisNo** [comment]
@agualbbus @radAragon Thanks for the feedback. I see your point about the details of the ant as a logo, but a simpler version of the logo could contain only the inverted λ. Maybe the ant would not seem so much detailed then. I'm thinking about using various versions of this ant as illustrations for the documentation.
